paths:
  /api/products/:
    get:
      summary: Obtener todos los productos
      tags:
        - Products
      responses: 
        '200':
          description: Productos obtenidos satisfactoriamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor al obtener los productos

  /api/products/{id}:
    get:
      summary: Obtener un producto por su id
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema: 
            $type: string
          description: id del producto deseado
      responses: 
        '200':
          description: Producto obtenido satisfactoriamente
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor al obtener el producto
  schemas:
    Product: 
      type: Object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerado por la BDD de Mongo
        title:
          type: string
          description: Descripci칩n del producto
        description:
          type: string
          description: Nombre del producto
        price:
          type: number
          description: Precio del producto
        stock:
          type: number
          description: Cantidad disponible
        category:
          type: string
          description: Categoria del producto
        status:
          type: boolean
          description: Si el producto est치 habilitado
        code:
          type: string
          description: C칩digo del producto. Funciona como index
        thumbnails:
          type: array
          description: Im치genes del producto
      example:
        _id: ObjectId('45fg4jn426')  
        title: 'Adidas Forum'
        description: 'Sneakers Adidas negras'
        stock: 13
        category: 'Sneakers'
        status: true
        code: '12jf38'
        thumbnails: []